# Generated by Django 6.0 on 2025-12-31 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasklists',
            name='task_status',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tasklists',
            name='task_time',
            field=models.TextField(blank=True, null=True),
        ),
    ]
